### PR TITLE
Fix build errors

### LINKED ISSUE #6: Libraries in deps/linux/lib/ can not be used when making a shared object
Numerous errors arise when building the example `main.go`, such as:

```
/usr/bin/ld: src/github.com/discordapp/lilliput/deps/linux/lib/libavcodec.a(bsf.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: src/github.com/discordapp/lilliput/deps/linux/lib/libavcodec.a(vp8dsp_init.o): relocation R_X86_64_32S against hidden symbol `ff_put_vp8_pixels8_mmx' can not be used when making a shared object
```
Tested environments:
* go1.7.4 linux/amd64 + gcc version 6.3.0 20170516 (Debian 6.3.0-18)
* go1.9.2 linux/amd64 + gcc version 6.4.0 (Gentoo Hardened 6.4.0 p1.1)

Thanks.

### PR DESCRIPTION
**Pull request by mapx**
Fixes #6 #7

### CODE REVIEW

**Comment by brian-armstrong-discord** [comment]
Hi @mapx 

Thanks for the patch.

Unfortunately, this would be a non-starter for us. Coupling the static libs with Go is useful for other users who want to use this package. It's also useful for us at Discord since it removes the dependencies needed to build this. I think it's handy to be able to build libs independently but users should not have to do this, especially given how long it takes and how many tools are required to do it.

Looking at #6 I was thinking the fix may be something like https://blog.hashbangbash.com/2014/04/linking-golang-statically/. As it is, I believe the libraries presently work on Ubuntu so it may just be a matter of getting them to work on other distros.

**Comment by mapx** [comment]
Neither
`go build --ldflags '-extldflags "-static"' examples/main.go`
nor
`go build -compiler gccgo --gccgoflags "-static" examples/main.go`
works on:
* go1.9.2 linux/amd64 + gcc version 6.4.0 (Gentoo Hardened 6.4.0 p1.1) 
* go1.7.4 linux/amd64 + gcc version 6.3.0 20170516 (Debian 6.3.0-18)

I'm not familiar with Golang and am still trying to build the example. Thanks for your reply :)

**Comment by brian-armstrong-discord** [comment]
Ah, that's too bad. What error did you get with the first? Same as before?

**Comment by mapx** [comment]
On `go1.7.4 linux/amd64 + gcc version 6.3.0 20170516 (Debian 6.3.0-18)`, the two commands result in almost the same error like before, say:
```
/usr/bin/ld: ../src/github.com/discordapp/lilliput/deps/linux/lib/libwebp.a(libwebpdsp_sse41_la-enc_sse41.o): relocation R_X86_64_32S against hidden symbol `VP8DspScan' can not be used when making a shared object
/usr/bin/ld: ../src/github.com/discordapp/lilliput/deps/linux/lib/libz.a(gzwrite.o): relocation R_X86_64_32S against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
```
Most of the error lines suggest the user recompile these libraries with -fPIC.
 
On `go1.9.2 linux/amd64 + gcc version 6.4.0 (Gentoo Hardened 6.4.0 p1.1)`, `gccgo` was not enabled yet.
While the only available command
`go build --ldflags '-extldflags "-static"' examples/main.go`
outputs almost the same error.

BTW,  though my PR makes it successful to build, the target executable fails to work with valid parameters and ends with:
```
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x55c0fa3dad00, 0xc420014110)
        /usr/lib/go-1.7/src/runtime/panic.go:500 +0x1a1
github.com/discordapp/lilliput.newOpenCVDecoder(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /tmp/src/github.com/discordapp/lilliput/opencv.go:230 +0x332
github.com/discordapp/lilliput.NewDecoder(0x0, 0x0, 0x0, 0x0, 0x0, 0x55fc80fca580, 0xc420018330)
        /tmp/src/github.com/discordapp/lilliput/lilliput.go:62 +0xc4
main.main()
        /tmp/src/github.com/discordapp/lilliput/examples/main.go:43 +0x2d0
```

**Comment by brian-armstrong-discord** [comment]
The error may just be the example being somewhat lazy about proper error checking. It doesn't check if the filename provided exists, and I have a feeling that's what's going on there.

**Comment by mapx** [comment]
Awesome! You are right. The executable is cool.

**Comment by brian-armstrong-discord** [comment]
👍 Glad that works at least.

I'll poke at the libraries a bit more in a Debian VM and see if I can get that working without removing everything

**Comment by joostshao** [comment]
```
/usr/bin/ld: ./deps/linux/lib/libavutil.a(cpu.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ./deps/linux/lib/libavutil.a(error.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ./deps/linux/lib/libavutil.a(eval.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ./deps/linux/lib/libavutil.a(file_open.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: 最后的链结失败: 输出不可表示的节
collect2: error: ld returned 1 exit status
➜  lilliput git:(master) ✗ go build -compiler gccgo --gccgoflags "-static" examples/main.go
go build: when using gccgo toolchain, please pass compiler flags using -gccgoflags, not -gcflags
# command-line-arguments
/usr/bin/ld: dynamic STT_GNU_IFUNC symbol `sin' with pointer equality in `/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libm.a(s_sin.o)' can not be used when making an executable; recompile with -fPIE and relink with -pie
collect2: error: ld returned 1 exit status

```

**Comment by lookapanda** [comment]
Is there anything new on this? I'm trying to automate building my library (that is using lilliput) through GitLab CI, but it fails because of #6

**Comment by brian-armstrong-discord** [comment]
I'm going to close this since this isn't the approach we're looking for, but the open Issue (#6) is still relevant.

**Pull request closed without merging**
